<?xml version="1.0"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:si="http://soapinterop.org/xsd" xmlns:tns="http://www.bigislandcolor.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.bigislandcolor.com/">
	<message name="ICRequest">
		<part name="imageInputURL" type="xsd:string" />
		<part name="imageOutputFilename" type="xsd:string" />
		<part name="flatten" type="xsd:boolean" />
	</message>
	<message name="ICResponse">
		<part name="return" type="xsd:string" />
	</message>
	<portType name="ICPortType">
		<operation name="imageConvert">
			<input message="tns:ICRequest" />
			<output message="tns:ICResponse" />
		</operation>
	</portType>
	<binding name="ICBinding" type="tns:ICPortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="imageConvert">
			<soap:operation soapAction="http://www.bigislandcolor.com/icserver.php" style="rpc" />
			<input>
				<soap:body use="literal" namespace="http://www.bigislandcolor.com/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output>
				<soap:body use="literal" namespace="http://www.bigislandcolor.com/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>
	</binding>
	<service name="imageConvert">
		<port name="ICPort" binding="tns:ICBinding">
			<soap:address location="http://www.bigislandcolor.com/icserver.php" />
		</port>
	</service>
</definitions>