<html>
	<head>
		<title>www.FreshScore.com</title>
	</head>
	<frameset rows="0,*" cols="*" border="no" frameborder="0" framespacing="0">
		<frame name="ddns_top" src="" scrolling="no" noresize="1" marginwidth="0" marginheight="0" frameborder="0">
			<frame name="ddns_frame" src="http://www.sedoparking.com/freshscore.com" noresize="1" marginwidth="0"
				marginheight="0" frameborder="0">
	</frameset>
	<noframes>
		<p>
			Your browser does not support frames. Please
			<a href="http://www.sedoparking.com/freshscore.com">click here</a>
			to continue.
		</p>
	</noframes>
</html><!--template -->