<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="IDutchservice"
	targetNamespace="http://eBob42.org/" xmlns:tns="http://eBob42.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/">
	<message name="NumToStr0Request">
		<part name="Num" type="xs:int" />
	</message>
	<message name="NumToStr0Response">
		<part name="return" type="xs:string" />
	</message>
	<portType name="IDutch">
		<operation name="NumToStr">
			<input message="tns:NumToStr0Request" />
			<output message="tns:NumToStr0Response" />
		</operation>
	</portType>
	<binding name="IDutchbinding" type="tns:IDutch">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="NumToStr">
			<soap:operation soapAction="urn:Dutch-IDutch#NumToStr" style="rpc" />
			<input message="tns:NumToStr0Request">
				<soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:Dutch-IDutch" />
			</input>
			<output message="tns:NumToStr0Response">
				<soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:Dutch-IDutch" />
			</output>
		</operation>
	</binding>
	<service name="IDutchservice">
		<port name="IDutchPort" binding="tns:IDutchbinding">
			<soap:address location="http://www.ebob42.com/cgi-bin/NumberToWordsInDutch.exe/soap/IDutch" />
		</port>
	</service>
</definitions>