## Makefile for the cpp exmaples

compile:

	g++ CRectangleSimple.cpp -o simple
	g++ Two.cpp -o two
	g++ Nested.cpp -o nested
	g++ NestedOfNested.cpp -o nestedOfNested
	g++ Person.cpp -o person
	g++ StructSample.cpp -o struct
	g++ EnumSample.cpp -o enum

run:

	./simple;
	./two;
	./nested;
	./nestedOfNested;
	./person;
	./struct;
	./enum;

clean:

	rm -f *.cpp;
	rm -f *.hpp;
	rm ./simple ./two ./nested ./nestedOfNested ./person ./struct ./enum

