package de.uniluebeck.sourcegen.nature;

public enum Nature {
	DOMAIN_SERIALIZER, DOMAIN_API, DOMAIN_SECURITY, DOMAIN_PACKETIZER, DOMAIN_WEBSERVICE,

	LANGUAGE_JAVA, LANGUAGE_C, LANGUAGE_CPP, LANGUAGE_NESC

}
